markdown: rdiscount
permalink: /blog/:title
paginate: 7
paginate_path: "/blog/page:num/"
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Nevada Dynamics
url: http://nevadadynamics.github.io
description: Nevada Dynamics is enabling long-range command and control of drones for hobbyists and commercial users
